spring:
  application:
    name: rest-api-example
  datasource:
    url: jdbc:sqlite:./data/app.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    database-platform: com.example.api.config.hibernate.SQLiteDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
    com.example.api: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId}] %logger{36} - %msg%n'
message:
  encoding:
    charset: UTF-8
springdoc:
  swagger-ui:
    enabled: ${swagger.ui.enabled:true}
